// Generated by gencpp from file quadruped_ctrl/QuadrupedCmdResponse.msg
// DO NOT EDIT!


#ifndef QUADRUPED_CTRL_MESSAGE_QUADRUPEDCMDRESPONSE_H
#define QUADRUPED_CTRL_MESSAGE_QUADRUPEDCMDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quadruped_ctrl
{
template <class ContainerAllocator>
struct QuadrupedCmdResponse_
{
  typedef QuadrupedCmdResponse_<ContainerAllocator> Type;

  QuadrupedCmdResponse_()
    : result(0)
    , description()  {
    }
  QuadrupedCmdResponse_(const ContainerAllocator& _alloc)
    : result(0)
    , description(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _description_type;
  _description_type description;





  typedef boost::shared_ptr< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QuadrupedCmdResponse_

typedef ::quadruped_ctrl::QuadrupedCmdResponse_<std::allocator<void> > QuadrupedCmdResponse;

typedef boost::shared_ptr< ::quadruped_ctrl::QuadrupedCmdResponse > QuadrupedCmdResponsePtr;
typedef boost::shared_ptr< ::quadruped_ctrl::QuadrupedCmdResponse const> QuadrupedCmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator1> & lhs, const ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.description == rhs.description;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator1> & lhs, const ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadruped_ctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "124eeb8e12f7acaa56b57d9a3c86ff45";
  }

  static const char* value(const ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x124eeb8e12f7acaaULL;
  static const uint64_t static_value2 = 0x56b57d9a3c86ff45ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadruped_ctrl/QuadrupedCmdResponse";
  }

  static const char* value(const ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 result				#0:success, -1:false\n"
"string description   #relative description\n"
"\n"
;
  }

  static const char* value(const ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadrupedCmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadruped_ctrl::QuadrupedCmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int16_t>::stream(s, indent + "  ", v.result);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADRUPED_CTRL_MESSAGE_QUADRUPEDCMDRESPONSE_H
