// Generated by gencpp from file quadruped_ctrl/QuadrupedCmdRequest.msg
// DO NOT EDIT!


#ifndef QUADRUPED_CTRL_MESSAGE_QUADRUPEDCMDREQUEST_H
#define QUADRUPED_CTRL_MESSAGE_QUADRUPEDCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quadruped_ctrl
{
template <class ContainerAllocator>
struct QuadrupedCmdRequest_
{
  typedef QuadrupedCmdRequest_<ContainerAllocator> Type;

  QuadrupedCmdRequest_()
    : cmd(0)  {
    }
  QuadrupedCmdRequest_(const ContainerAllocator& _alloc)
    : cmd(0)  {
  (void)_alloc;
    }



   typedef int16_t _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QuadrupedCmdRequest_

typedef ::quadruped_ctrl::QuadrupedCmdRequest_<std::allocator<void> > QuadrupedCmdRequest;

typedef boost::shared_ptr< ::quadruped_ctrl::QuadrupedCmdRequest > QuadrupedCmdRequestPtr;
typedef boost::shared_ptr< ::quadruped_ctrl::QuadrupedCmdRequest const> QuadrupedCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator1> & lhs, const ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator1> & lhs, const ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadruped_ctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e12b32aac6266778a9aa3b101cf7c33e";
  }

  static const char* value(const ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe12b32aac6266778ULL;
  static const uint64_t static_value2 = 0xa9aa3b101cf7c33eULL;
};

template<class ContainerAllocator>
struct DataType< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadruped_ctrl/QuadrupedCmdRequest";
  }

  static const char* value(const ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 cmd\n"
;
  }

  static const char* value(const ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadrupedCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadruped_ctrl::QuadrupedCmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int16_t>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADRUPED_CTRL_MESSAGE_QUADRUPEDCMDREQUEST_H
