// Generated by gencpp from file quadruped_ctrl/QuadrupedCmd.msg
// DO NOT EDIT!


#ifndef QUADRUPED_CTRL_MESSAGE_QUADRUPEDCMD_H
#define QUADRUPED_CTRL_MESSAGE_QUADRUPEDCMD_H

#include <ros/service_traits.h>


#include <quadruped_ctrl/QuadrupedCmdRequest.h>
#include <quadruped_ctrl/QuadrupedCmdResponse.h>


namespace quadruped_ctrl
{

struct QuadrupedCmd
{

typedef QuadrupedCmdRequest Request;
typedef QuadrupedCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QuadrupedCmd
} // namespace quadruped_ctrl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::quadruped_ctrl::QuadrupedCmd > {
  static const char* value()
  {
    return "f5d998487ff22f19faff84885516d9ae";
  }

  static const char* value(const ::quadruped_ctrl::QuadrupedCmd&) { return value(); }
};

template<>
struct DataType< ::quadruped_ctrl::QuadrupedCmd > {
  static const char* value()
  {
    return "quadruped_ctrl/QuadrupedCmd";
  }

  static const char* value(const ::quadruped_ctrl::QuadrupedCmd&) { return value(); }
};


// service_traits::MD5Sum< ::quadruped_ctrl::QuadrupedCmdRequest> should match
// service_traits::MD5Sum< ::quadruped_ctrl::QuadrupedCmd >
template<>
struct MD5Sum< ::quadruped_ctrl::QuadrupedCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::quadruped_ctrl::QuadrupedCmd >::value();
  }
  static const char* value(const ::quadruped_ctrl::QuadrupedCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::quadruped_ctrl::QuadrupedCmdRequest> should match
// service_traits::DataType< ::quadruped_ctrl::QuadrupedCmd >
template<>
struct DataType< ::quadruped_ctrl::QuadrupedCmdRequest>
{
  static const char* value()
  {
    return DataType< ::quadruped_ctrl::QuadrupedCmd >::value();
  }
  static const char* value(const ::quadruped_ctrl::QuadrupedCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::quadruped_ctrl::QuadrupedCmdResponse> should match
// service_traits::MD5Sum< ::quadruped_ctrl::QuadrupedCmd >
template<>
struct MD5Sum< ::quadruped_ctrl::QuadrupedCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::quadruped_ctrl::QuadrupedCmd >::value();
  }
  static const char* value(const ::quadruped_ctrl::QuadrupedCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::quadruped_ctrl::QuadrupedCmdResponse> should match
// service_traits::DataType< ::quadruped_ctrl::QuadrupedCmd >
template<>
struct DataType< ::quadruped_ctrl::QuadrupedCmdResponse>
{
  static const char* value()
  {
    return DataType< ::quadruped_ctrl::QuadrupedCmd >::value();
  }
  static const char* value(const ::quadruped_ctrl::QuadrupedCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QUADRUPED_CTRL_MESSAGE_QUADRUPEDCMD_H
