# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from whole_body_state_msgs/WholeBodyController.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg
import whole_body_state_msgs.msg

class WholeBodyController(genpy.Message):
  _md5sum = "9d7e81de51b0c42689581611cacdaaec"
  _type = "whole_body_state_msgs/WholeBodyController"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# This message describes the whole-body state of controller.
#
# A whole-body controller state is defined by the desired, actual, and
# error of the whole-body state of the system. The description of
# every element is defined in their respective messages.
#
# The header specifies the time at which the trajectory is published.


std_msgs/Header header

# Desired whole-body state
whole_body_state_msgs/WholeBodyState desired

# Actual whole-body state
whole_body_state_msgs/WholeBodyState actual

# Error whole-body state
whole_body_state_msgs/WholeBodyState error

# Command state
whole_body_state_msgs/JointCommand[] command

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: whole_body_state_msgs/WholeBodyState
# This message describes the whole-body state of rigid body system.
#
# A whole-body state is defined by the centroidal, joints and contact states.
# The description of every element is defined in their respective
# messages. This state is described in respective time.
#
# The centroidal state describes
#  * the position, velocity and acceleration of the CoM,
#  * the base orientation and angular velocity, and
#  * the linear and angular momentum and their rates.
#
# The joint states describes:
#  * the joint name
#  * the position of the joint (rad or m),
#  * the velocity of the joint (rad/s or m/s),
#  * the effort that is applied in the joint (Nm or N).
# The contact state describes
#  * the frame name
#  * the pose of the contact,
#  * the velocity of the contact, and
#  * the wrench of the contact
# The header specifies the time at which the state is published.


std_msgs/Header header

# This represent the time state
float64 time

# This represents the base state (CoM motion, angular motion and centroidal momenta)
whole_body_state_msgs/CentroidalState centroidal

# This represents the joint state (position, velocity, acceleration and effort)
whole_body_state_msgs/JointState[] joints

# This represents the end-effector state (cartesian position and contact forces)
whole_body_state_msgs/ContactState[] contacts

================================================================================
MSG: whole_body_state_msgs/CentroidalState
# This message describes the states of a centroidal state.
#
# The centroidal state is defined by:
#  * the position, velocity and acceleration of the CoM,
#  * the base orientation and angular velocity, and
#  * the linear and angular momentum and their rates.
# where each quantity is expressed in the world frame.

# Center of mass
geometry_msgs/Vector3 com_position
geometry_msgs/Vector3 com_velocity

# Base orientation
geometry_msgs/Quaternion base_orientation
geometry_msgs/Vector3 base_angular_velocity

# Linear and angular momentum
geometry_msgs/Twist momenta
geometry_msgs/Twist momenta_rate

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: whole_body_state_msgs/JointState
# This message describes the state of an actuated joints.
#
# The state of each joint (revolute or prismatic) is defined by:
#  * the joint name
#  * the position of the joint (rad or m),
#  * the velocity of the joint (rad/s or m/s),
#  * the acceleration of the joint (rad/s^2 or m/s^2), and
#  * the effort that is applied in the joint (Nm or N).
#
# Each joint is uniquely identified by its name


# Name of the joint
string name

# States of the joint
float64 position
float64 velocity
float64 acceleration
float64 effort

================================================================================
MSG: whole_body_state_msgs/ContactState
# This message describes the state of contact or end-effector body.
#
# The contact state is expressed in the world frame. A contact state is
# defined by:
#  * type of contact
#  * status of the contact
#  * the frame name
#  * the pose of the contact,
#  * the velocity of the contact,
#  * the wrench of the contact
#  * the normal vector that defines the surface
#  * the friction coefficient of the surface
#  * its classified state, if available

# Type of contact identifiers
uint8 LOCOMOTION   = 0
uint8 MANIPULATION = 1

# Type of contact states
uint8 UNKNOWN  = 0  # 0 because it's the default for int8
uint8 INACTIVE = 1
uint8 ACTIVE   = 2
uint8 SLIPPING = 3

# Name of the contact body
string name

# Type of contact
uint8 type

# Contact status (e.g. from a contact state estimator)
uint8 status

# State of the contact body
geometry_msgs/Pose pose
geometry_msgs/Twist velocity
geometry_msgs/Wrench wrench
geometry_msgs/Vector3 surface_normal
float64 friction_coefficient

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Wrench
# This represents force in free space, separated into
# its linear and angular parts.
Vector3  force
Vector3  torque

================================================================================
MSG: whole_body_state_msgs/JointCommand
# This message describes the state of joint command.
#
# The state of each command (revolute or prismatic) is defined by:
#  * the total command to the joint (Nm or N),
#  * the feedforward command component (Nm or N), and
#  * the feedback command component (Nm or N)
#
# Each commanded joint is uniquely identified by its name


string name
float64 total
float64 feedforward
float64 feedback
"""
  __slots__ = ['header','desired','actual','error','command']
  _slot_types = ['std_msgs/Header','whole_body_state_msgs/WholeBodyState','whole_body_state_msgs/WholeBodyState','whole_body_state_msgs/WholeBodyState','whole_body_state_msgs/JointCommand[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,desired,actual,error,command

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WholeBodyController, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.desired is None:
        self.desired = whole_body_state_msgs.msg.WholeBodyState()
      if self.actual is None:
        self.actual = whole_body_state_msgs.msg.WholeBodyState()
      if self.error is None:
        self.error = whole_body_state_msgs.msg.WholeBodyState()
      if self.command is None:
        self.command = []
    else:
      self.header = std_msgs.msg.Header()
      self.desired = whole_body_state_msgs.msg.WholeBodyState()
      self.actual = whole_body_state_msgs.msg.WholeBodyState()
      self.error = whole_body_state_msgs.msg.WholeBodyState()
      self.command = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.desired.header.seq, _x.desired.header.stamp.secs, _x.desired.header.stamp.nsecs))
      _x = self.desired.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_26d().pack(_x.desired.time, _x.desired.centroidal.com_position.x, _x.desired.centroidal.com_position.y, _x.desired.centroidal.com_position.z, _x.desired.centroidal.com_velocity.x, _x.desired.centroidal.com_velocity.y, _x.desired.centroidal.com_velocity.z, _x.desired.centroidal.base_orientation.x, _x.desired.centroidal.base_orientation.y, _x.desired.centroidal.base_orientation.z, _x.desired.centroidal.base_orientation.w, _x.desired.centroidal.base_angular_velocity.x, _x.desired.centroidal.base_angular_velocity.y, _x.desired.centroidal.base_angular_velocity.z, _x.desired.centroidal.momenta.linear.x, _x.desired.centroidal.momenta.linear.y, _x.desired.centroidal.momenta.linear.z, _x.desired.centroidal.momenta.angular.x, _x.desired.centroidal.momenta.angular.y, _x.desired.centroidal.momenta.angular.z, _x.desired.centroidal.momenta_rate.linear.x, _x.desired.centroidal.momenta_rate.linear.y, _x.desired.centroidal.momenta_rate.linear.z, _x.desired.centroidal.momenta_rate.angular.x, _x.desired.centroidal.momenta_rate.angular.y, _x.desired.centroidal.momenta_rate.angular.z))
      length = len(self.desired.joints)
      buff.write(_struct_I.pack(length))
      for val1 in self.desired.joints:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_4d().pack(_x.position, _x.velocity, _x.acceleration, _x.effort))
      length = len(self.desired.contacts)
      buff.write(_struct_I.pack(length))
      for val1 in self.desired.contacts:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2B().pack(_x.type, _x.status))
        _v1 = val1.pose
        _v2 = _v1.position
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v3 = _v1.orientation
        _x = _v3
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v4 = val1.velocity
        _v5 = _v4.linear
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v6 = _v4.angular
        _x = _v6
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v7 = val1.wrench
        _v8 = _v7.force
        _x = _v8
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v9 = _v7.torque
        _x = _v9
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v10 = val1.surface_normal
        _x = _v10
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.friction_coefficient
        buff.write(_get_struct_d().pack(_x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.actual.header.seq, _x.actual.header.stamp.secs, _x.actual.header.stamp.nsecs))
      _x = self.actual.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_26d().pack(_x.actual.time, _x.actual.centroidal.com_position.x, _x.actual.centroidal.com_position.y, _x.actual.centroidal.com_position.z, _x.actual.centroidal.com_velocity.x, _x.actual.centroidal.com_velocity.y, _x.actual.centroidal.com_velocity.z, _x.actual.centroidal.base_orientation.x, _x.actual.centroidal.base_orientation.y, _x.actual.centroidal.base_orientation.z, _x.actual.centroidal.base_orientation.w, _x.actual.centroidal.base_angular_velocity.x, _x.actual.centroidal.base_angular_velocity.y, _x.actual.centroidal.base_angular_velocity.z, _x.actual.centroidal.momenta.linear.x, _x.actual.centroidal.momenta.linear.y, _x.actual.centroidal.momenta.linear.z, _x.actual.centroidal.momenta.angular.x, _x.actual.centroidal.momenta.angular.y, _x.actual.centroidal.momenta.angular.z, _x.actual.centroidal.momenta_rate.linear.x, _x.actual.centroidal.momenta_rate.linear.y, _x.actual.centroidal.momenta_rate.linear.z, _x.actual.centroidal.momenta_rate.angular.x, _x.actual.centroidal.momenta_rate.angular.y, _x.actual.centroidal.momenta_rate.angular.z))
      length = len(self.actual.joints)
      buff.write(_struct_I.pack(length))
      for val1 in self.actual.joints:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_4d().pack(_x.position, _x.velocity, _x.acceleration, _x.effort))
      length = len(self.actual.contacts)
      buff.write(_struct_I.pack(length))
      for val1 in self.actual.contacts:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2B().pack(_x.type, _x.status))
        _v11 = val1.pose
        _v12 = _v11.position
        _x = _v12
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v13 = _v11.orientation
        _x = _v13
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v14 = val1.velocity
        _v15 = _v14.linear
        _x = _v15
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v16 = _v14.angular
        _x = _v16
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v17 = val1.wrench
        _v18 = _v17.force
        _x = _v18
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v19 = _v17.torque
        _x = _v19
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v20 = val1.surface_normal
        _x = _v20
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.friction_coefficient
        buff.write(_get_struct_d().pack(_x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.error.header.seq, _x.error.header.stamp.secs, _x.error.header.stamp.nsecs))
      _x = self.error.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_26d().pack(_x.error.time, _x.error.centroidal.com_position.x, _x.error.centroidal.com_position.y, _x.error.centroidal.com_position.z, _x.error.centroidal.com_velocity.x, _x.error.centroidal.com_velocity.y, _x.error.centroidal.com_velocity.z, _x.error.centroidal.base_orientation.x, _x.error.centroidal.base_orientation.y, _x.error.centroidal.base_orientation.z, _x.error.centroidal.base_orientation.w, _x.error.centroidal.base_angular_velocity.x, _x.error.centroidal.base_angular_velocity.y, _x.error.centroidal.base_angular_velocity.z, _x.error.centroidal.momenta.linear.x, _x.error.centroidal.momenta.linear.y, _x.error.centroidal.momenta.linear.z, _x.error.centroidal.momenta.angular.x, _x.error.centroidal.momenta.angular.y, _x.error.centroidal.momenta.angular.z, _x.error.centroidal.momenta_rate.linear.x, _x.error.centroidal.momenta_rate.linear.y, _x.error.centroidal.momenta_rate.linear.z, _x.error.centroidal.momenta_rate.angular.x, _x.error.centroidal.momenta_rate.angular.y, _x.error.centroidal.momenta_rate.angular.z))
      length = len(self.error.joints)
      buff.write(_struct_I.pack(length))
      for val1 in self.error.joints:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_4d().pack(_x.position, _x.velocity, _x.acceleration, _x.effort))
      length = len(self.error.contacts)
      buff.write(_struct_I.pack(length))
      for val1 in self.error.contacts:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2B().pack(_x.type, _x.status))
        _v21 = val1.pose
        _v22 = _v21.position
        _x = _v22
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v23 = _v21.orientation
        _x = _v23
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v24 = val1.velocity
        _v25 = _v24.linear
        _x = _v25
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v26 = _v24.angular
        _x = _v26
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v27 = val1.wrench
        _v28 = _v27.force
        _x = _v28
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v29 = _v27.torque
        _x = _v29
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v30 = val1.surface_normal
        _x = _v30
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.friction_coefficient
        buff.write(_get_struct_d().pack(_x))
      length = len(self.command)
      buff.write(_struct_I.pack(length))
      for val1 in self.command:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_3d().pack(_x.total, _x.feedforward, _x.feedback))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.desired is None:
        self.desired = whole_body_state_msgs.msg.WholeBodyState()
      if self.actual is None:
        self.actual = whole_body_state_msgs.msg.WholeBodyState()
      if self.error is None:
        self.error = whole_body_state_msgs.msg.WholeBodyState()
      if self.command is None:
        self.command = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.desired.header.seq, _x.desired.header.stamp.secs, _x.desired.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.desired.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.desired.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 208
      (_x.desired.time, _x.desired.centroidal.com_position.x, _x.desired.centroidal.com_position.y, _x.desired.centroidal.com_position.z, _x.desired.centroidal.com_velocity.x, _x.desired.centroidal.com_velocity.y, _x.desired.centroidal.com_velocity.z, _x.desired.centroidal.base_orientation.x, _x.desired.centroidal.base_orientation.y, _x.desired.centroidal.base_orientation.z, _x.desired.centroidal.base_orientation.w, _x.desired.centroidal.base_angular_velocity.x, _x.desired.centroidal.base_angular_velocity.y, _x.desired.centroidal.base_angular_velocity.z, _x.desired.centroidal.momenta.linear.x, _x.desired.centroidal.momenta.linear.y, _x.desired.centroidal.momenta.linear.z, _x.desired.centroidal.momenta.angular.x, _x.desired.centroidal.momenta.angular.y, _x.desired.centroidal.momenta.angular.z, _x.desired.centroidal.momenta_rate.linear.x, _x.desired.centroidal.momenta_rate.linear.y, _x.desired.centroidal.momenta_rate.linear.z, _x.desired.centroidal.momenta_rate.angular.x, _x.desired.centroidal.momenta_rate.angular.y, _x.desired.centroidal.momenta_rate.angular.z,) = _get_struct_26d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.desired.joints = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.JointState()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 32
        (_x.position, _x.velocity, _x.acceleration, _x.effort,) = _get_struct_4d().unpack(str[start:end])
        self.desired.joints.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.desired.contacts = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.ContactState()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 2
        (_x.type, _x.status,) = _get_struct_2B().unpack(str[start:end])
        _v31 = val1.pose
        _v32 = _v31.position
        _x = _v32
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v33 = _v31.orientation
        _x = _v33
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _v34 = val1.velocity
        _v35 = _v34.linear
        _x = _v35
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v36 = _v34.angular
        _x = _v36
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v37 = val1.wrench
        _v38 = _v37.force
        _x = _v38
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v39 = _v37.torque
        _x = _v39
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v40 = val1.surface_normal
        _x = _v40
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 8
        (val1.friction_coefficient,) = _get_struct_d().unpack(str[start:end])
        self.desired.contacts.append(val1)
      _x = self
      start = end
      end += 12
      (_x.actual.header.seq, _x.actual.header.stamp.secs, _x.actual.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.actual.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.actual.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 208
      (_x.actual.time, _x.actual.centroidal.com_position.x, _x.actual.centroidal.com_position.y, _x.actual.centroidal.com_position.z, _x.actual.centroidal.com_velocity.x, _x.actual.centroidal.com_velocity.y, _x.actual.centroidal.com_velocity.z, _x.actual.centroidal.base_orientation.x, _x.actual.centroidal.base_orientation.y, _x.actual.centroidal.base_orientation.z, _x.actual.centroidal.base_orientation.w, _x.actual.centroidal.base_angular_velocity.x, _x.actual.centroidal.base_angular_velocity.y, _x.actual.centroidal.base_angular_velocity.z, _x.actual.centroidal.momenta.linear.x, _x.actual.centroidal.momenta.linear.y, _x.actual.centroidal.momenta.linear.z, _x.actual.centroidal.momenta.angular.x, _x.actual.centroidal.momenta.angular.y, _x.actual.centroidal.momenta.angular.z, _x.actual.centroidal.momenta_rate.linear.x, _x.actual.centroidal.momenta_rate.linear.y, _x.actual.centroidal.momenta_rate.linear.z, _x.actual.centroidal.momenta_rate.angular.x, _x.actual.centroidal.momenta_rate.angular.y, _x.actual.centroidal.momenta_rate.angular.z,) = _get_struct_26d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.actual.joints = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.JointState()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 32
        (_x.position, _x.velocity, _x.acceleration, _x.effort,) = _get_struct_4d().unpack(str[start:end])
        self.actual.joints.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.actual.contacts = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.ContactState()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 2
        (_x.type, _x.status,) = _get_struct_2B().unpack(str[start:end])
        _v41 = val1.pose
        _v42 = _v41.position
        _x = _v42
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v43 = _v41.orientation
        _x = _v43
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _v44 = val1.velocity
        _v45 = _v44.linear
        _x = _v45
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v46 = _v44.angular
        _x = _v46
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v47 = val1.wrench
        _v48 = _v47.force
        _x = _v48
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v49 = _v47.torque
        _x = _v49
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v50 = val1.surface_normal
        _x = _v50
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 8
        (val1.friction_coefficient,) = _get_struct_d().unpack(str[start:end])
        self.actual.contacts.append(val1)
      _x = self
      start = end
      end += 12
      (_x.error.header.seq, _x.error.header.stamp.secs, _x.error.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.error.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.error.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 208
      (_x.error.time, _x.error.centroidal.com_position.x, _x.error.centroidal.com_position.y, _x.error.centroidal.com_position.z, _x.error.centroidal.com_velocity.x, _x.error.centroidal.com_velocity.y, _x.error.centroidal.com_velocity.z, _x.error.centroidal.base_orientation.x, _x.error.centroidal.base_orientation.y, _x.error.centroidal.base_orientation.z, _x.error.centroidal.base_orientation.w, _x.error.centroidal.base_angular_velocity.x, _x.error.centroidal.base_angular_velocity.y, _x.error.centroidal.base_angular_velocity.z, _x.error.centroidal.momenta.linear.x, _x.error.centroidal.momenta.linear.y, _x.error.centroidal.momenta.linear.z, _x.error.centroidal.momenta.angular.x, _x.error.centroidal.momenta.angular.y, _x.error.centroidal.momenta.angular.z, _x.error.centroidal.momenta_rate.linear.x, _x.error.centroidal.momenta_rate.linear.y, _x.error.centroidal.momenta_rate.linear.z, _x.error.centroidal.momenta_rate.angular.x, _x.error.centroidal.momenta_rate.angular.y, _x.error.centroidal.momenta_rate.angular.z,) = _get_struct_26d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.error.joints = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.JointState()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 32
        (_x.position, _x.velocity, _x.acceleration, _x.effort,) = _get_struct_4d().unpack(str[start:end])
        self.error.joints.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.error.contacts = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.ContactState()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 2
        (_x.type, _x.status,) = _get_struct_2B().unpack(str[start:end])
        _v51 = val1.pose
        _v52 = _v51.position
        _x = _v52
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v53 = _v51.orientation
        _x = _v53
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _v54 = val1.velocity
        _v55 = _v54.linear
        _x = _v55
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v56 = _v54.angular
        _x = _v56
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v57 = val1.wrench
        _v58 = _v57.force
        _x = _v58
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v59 = _v57.torque
        _x = _v59
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v60 = val1.surface_normal
        _x = _v60
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 8
        (val1.friction_coefficient,) = _get_struct_d().unpack(str[start:end])
        self.error.contacts.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.command = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.JointCommand()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 24
        (_x.total, _x.feedforward, _x.feedback,) = _get_struct_3d().unpack(str[start:end])
        self.command.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.desired.header.seq, _x.desired.header.stamp.secs, _x.desired.header.stamp.nsecs))
      _x = self.desired.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_26d().pack(_x.desired.time, _x.desired.centroidal.com_position.x, _x.desired.centroidal.com_position.y, _x.desired.centroidal.com_position.z, _x.desired.centroidal.com_velocity.x, _x.desired.centroidal.com_velocity.y, _x.desired.centroidal.com_velocity.z, _x.desired.centroidal.base_orientation.x, _x.desired.centroidal.base_orientation.y, _x.desired.centroidal.base_orientation.z, _x.desired.centroidal.base_orientation.w, _x.desired.centroidal.base_angular_velocity.x, _x.desired.centroidal.base_angular_velocity.y, _x.desired.centroidal.base_angular_velocity.z, _x.desired.centroidal.momenta.linear.x, _x.desired.centroidal.momenta.linear.y, _x.desired.centroidal.momenta.linear.z, _x.desired.centroidal.momenta.angular.x, _x.desired.centroidal.momenta.angular.y, _x.desired.centroidal.momenta.angular.z, _x.desired.centroidal.momenta_rate.linear.x, _x.desired.centroidal.momenta_rate.linear.y, _x.desired.centroidal.momenta_rate.linear.z, _x.desired.centroidal.momenta_rate.angular.x, _x.desired.centroidal.momenta_rate.angular.y, _x.desired.centroidal.momenta_rate.angular.z))
      length = len(self.desired.joints)
      buff.write(_struct_I.pack(length))
      for val1 in self.desired.joints:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_4d().pack(_x.position, _x.velocity, _x.acceleration, _x.effort))
      length = len(self.desired.contacts)
      buff.write(_struct_I.pack(length))
      for val1 in self.desired.contacts:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2B().pack(_x.type, _x.status))
        _v61 = val1.pose
        _v62 = _v61.position
        _x = _v62
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v63 = _v61.orientation
        _x = _v63
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v64 = val1.velocity
        _v65 = _v64.linear
        _x = _v65
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v66 = _v64.angular
        _x = _v66
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v67 = val1.wrench
        _v68 = _v67.force
        _x = _v68
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v69 = _v67.torque
        _x = _v69
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v70 = val1.surface_normal
        _x = _v70
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.friction_coefficient
        buff.write(_get_struct_d().pack(_x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.actual.header.seq, _x.actual.header.stamp.secs, _x.actual.header.stamp.nsecs))
      _x = self.actual.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_26d().pack(_x.actual.time, _x.actual.centroidal.com_position.x, _x.actual.centroidal.com_position.y, _x.actual.centroidal.com_position.z, _x.actual.centroidal.com_velocity.x, _x.actual.centroidal.com_velocity.y, _x.actual.centroidal.com_velocity.z, _x.actual.centroidal.base_orientation.x, _x.actual.centroidal.base_orientation.y, _x.actual.centroidal.base_orientation.z, _x.actual.centroidal.base_orientation.w, _x.actual.centroidal.base_angular_velocity.x, _x.actual.centroidal.base_angular_velocity.y, _x.actual.centroidal.base_angular_velocity.z, _x.actual.centroidal.momenta.linear.x, _x.actual.centroidal.momenta.linear.y, _x.actual.centroidal.momenta.linear.z, _x.actual.centroidal.momenta.angular.x, _x.actual.centroidal.momenta.angular.y, _x.actual.centroidal.momenta.angular.z, _x.actual.centroidal.momenta_rate.linear.x, _x.actual.centroidal.momenta_rate.linear.y, _x.actual.centroidal.momenta_rate.linear.z, _x.actual.centroidal.momenta_rate.angular.x, _x.actual.centroidal.momenta_rate.angular.y, _x.actual.centroidal.momenta_rate.angular.z))
      length = len(self.actual.joints)
      buff.write(_struct_I.pack(length))
      for val1 in self.actual.joints:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_4d().pack(_x.position, _x.velocity, _x.acceleration, _x.effort))
      length = len(self.actual.contacts)
      buff.write(_struct_I.pack(length))
      for val1 in self.actual.contacts:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2B().pack(_x.type, _x.status))
        _v71 = val1.pose
        _v72 = _v71.position
        _x = _v72
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v73 = _v71.orientation
        _x = _v73
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v74 = val1.velocity
        _v75 = _v74.linear
        _x = _v75
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v76 = _v74.angular
        _x = _v76
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v77 = val1.wrench
        _v78 = _v77.force
        _x = _v78
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v79 = _v77.torque
        _x = _v79
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v80 = val1.surface_normal
        _x = _v80
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.friction_coefficient
        buff.write(_get_struct_d().pack(_x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.error.header.seq, _x.error.header.stamp.secs, _x.error.header.stamp.nsecs))
      _x = self.error.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_26d().pack(_x.error.time, _x.error.centroidal.com_position.x, _x.error.centroidal.com_position.y, _x.error.centroidal.com_position.z, _x.error.centroidal.com_velocity.x, _x.error.centroidal.com_velocity.y, _x.error.centroidal.com_velocity.z, _x.error.centroidal.base_orientation.x, _x.error.centroidal.base_orientation.y, _x.error.centroidal.base_orientation.z, _x.error.centroidal.base_orientation.w, _x.error.centroidal.base_angular_velocity.x, _x.error.centroidal.base_angular_velocity.y, _x.error.centroidal.base_angular_velocity.z, _x.error.centroidal.momenta.linear.x, _x.error.centroidal.momenta.linear.y, _x.error.centroidal.momenta.linear.z, _x.error.centroidal.momenta.angular.x, _x.error.centroidal.momenta.angular.y, _x.error.centroidal.momenta.angular.z, _x.error.centroidal.momenta_rate.linear.x, _x.error.centroidal.momenta_rate.linear.y, _x.error.centroidal.momenta_rate.linear.z, _x.error.centroidal.momenta_rate.angular.x, _x.error.centroidal.momenta_rate.angular.y, _x.error.centroidal.momenta_rate.angular.z))
      length = len(self.error.joints)
      buff.write(_struct_I.pack(length))
      for val1 in self.error.joints:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_4d().pack(_x.position, _x.velocity, _x.acceleration, _x.effort))
      length = len(self.error.contacts)
      buff.write(_struct_I.pack(length))
      for val1 in self.error.contacts:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2B().pack(_x.type, _x.status))
        _v81 = val1.pose
        _v82 = _v81.position
        _x = _v82
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v83 = _v81.orientation
        _x = _v83
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v84 = val1.velocity
        _v85 = _v84.linear
        _x = _v85
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v86 = _v84.angular
        _x = _v86
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v87 = val1.wrench
        _v88 = _v87.force
        _x = _v88
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v89 = _v87.torque
        _x = _v89
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v90 = val1.surface_normal
        _x = _v90
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.friction_coefficient
        buff.write(_get_struct_d().pack(_x))
      length = len(self.command)
      buff.write(_struct_I.pack(length))
      for val1 in self.command:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_3d().pack(_x.total, _x.feedforward, _x.feedback))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.desired is None:
        self.desired = whole_body_state_msgs.msg.WholeBodyState()
      if self.actual is None:
        self.actual = whole_body_state_msgs.msg.WholeBodyState()
      if self.error is None:
        self.error = whole_body_state_msgs.msg.WholeBodyState()
      if self.command is None:
        self.command = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.desired.header.seq, _x.desired.header.stamp.secs, _x.desired.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.desired.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.desired.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 208
      (_x.desired.time, _x.desired.centroidal.com_position.x, _x.desired.centroidal.com_position.y, _x.desired.centroidal.com_position.z, _x.desired.centroidal.com_velocity.x, _x.desired.centroidal.com_velocity.y, _x.desired.centroidal.com_velocity.z, _x.desired.centroidal.base_orientation.x, _x.desired.centroidal.base_orientation.y, _x.desired.centroidal.base_orientation.z, _x.desired.centroidal.base_orientation.w, _x.desired.centroidal.base_angular_velocity.x, _x.desired.centroidal.base_angular_velocity.y, _x.desired.centroidal.base_angular_velocity.z, _x.desired.centroidal.momenta.linear.x, _x.desired.centroidal.momenta.linear.y, _x.desired.centroidal.momenta.linear.z, _x.desired.centroidal.momenta.angular.x, _x.desired.centroidal.momenta.angular.y, _x.desired.centroidal.momenta.angular.z, _x.desired.centroidal.momenta_rate.linear.x, _x.desired.centroidal.momenta_rate.linear.y, _x.desired.centroidal.momenta_rate.linear.z, _x.desired.centroidal.momenta_rate.angular.x, _x.desired.centroidal.momenta_rate.angular.y, _x.desired.centroidal.momenta_rate.angular.z,) = _get_struct_26d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.desired.joints = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.JointState()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 32
        (_x.position, _x.velocity, _x.acceleration, _x.effort,) = _get_struct_4d().unpack(str[start:end])
        self.desired.joints.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.desired.contacts = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.ContactState()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 2
        (_x.type, _x.status,) = _get_struct_2B().unpack(str[start:end])
        _v91 = val1.pose
        _v92 = _v91.position
        _x = _v92
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v93 = _v91.orientation
        _x = _v93
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _v94 = val1.velocity
        _v95 = _v94.linear
        _x = _v95
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v96 = _v94.angular
        _x = _v96
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v97 = val1.wrench
        _v98 = _v97.force
        _x = _v98
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v99 = _v97.torque
        _x = _v99
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v100 = val1.surface_normal
        _x = _v100
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 8
        (val1.friction_coefficient,) = _get_struct_d().unpack(str[start:end])
        self.desired.contacts.append(val1)
      _x = self
      start = end
      end += 12
      (_x.actual.header.seq, _x.actual.header.stamp.secs, _x.actual.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.actual.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.actual.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 208
      (_x.actual.time, _x.actual.centroidal.com_position.x, _x.actual.centroidal.com_position.y, _x.actual.centroidal.com_position.z, _x.actual.centroidal.com_velocity.x, _x.actual.centroidal.com_velocity.y, _x.actual.centroidal.com_velocity.z, _x.actual.centroidal.base_orientation.x, _x.actual.centroidal.base_orientation.y, _x.actual.centroidal.base_orientation.z, _x.actual.centroidal.base_orientation.w, _x.actual.centroidal.base_angular_velocity.x, _x.actual.centroidal.base_angular_velocity.y, _x.actual.centroidal.base_angular_velocity.z, _x.actual.centroidal.momenta.linear.x, _x.actual.centroidal.momenta.linear.y, _x.actual.centroidal.momenta.linear.z, _x.actual.centroidal.momenta.angular.x, _x.actual.centroidal.momenta.angular.y, _x.actual.centroidal.momenta.angular.z, _x.actual.centroidal.momenta_rate.linear.x, _x.actual.centroidal.momenta_rate.linear.y, _x.actual.centroidal.momenta_rate.linear.z, _x.actual.centroidal.momenta_rate.angular.x, _x.actual.centroidal.momenta_rate.angular.y, _x.actual.centroidal.momenta_rate.angular.z,) = _get_struct_26d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.actual.joints = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.JointState()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 32
        (_x.position, _x.velocity, _x.acceleration, _x.effort,) = _get_struct_4d().unpack(str[start:end])
        self.actual.joints.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.actual.contacts = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.ContactState()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 2
        (_x.type, _x.status,) = _get_struct_2B().unpack(str[start:end])
        _v101 = val1.pose
        _v102 = _v101.position
        _x = _v102
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v103 = _v101.orientation
        _x = _v103
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _v104 = val1.velocity
        _v105 = _v104.linear
        _x = _v105
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v106 = _v104.angular
        _x = _v106
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v107 = val1.wrench
        _v108 = _v107.force
        _x = _v108
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v109 = _v107.torque
        _x = _v109
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v110 = val1.surface_normal
        _x = _v110
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 8
        (val1.friction_coefficient,) = _get_struct_d().unpack(str[start:end])
        self.actual.contacts.append(val1)
      _x = self
      start = end
      end += 12
      (_x.error.header.seq, _x.error.header.stamp.secs, _x.error.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.error.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.error.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 208
      (_x.error.time, _x.error.centroidal.com_position.x, _x.error.centroidal.com_position.y, _x.error.centroidal.com_position.z, _x.error.centroidal.com_velocity.x, _x.error.centroidal.com_velocity.y, _x.error.centroidal.com_velocity.z, _x.error.centroidal.base_orientation.x, _x.error.centroidal.base_orientation.y, _x.error.centroidal.base_orientation.z, _x.error.centroidal.base_orientation.w, _x.error.centroidal.base_angular_velocity.x, _x.error.centroidal.base_angular_velocity.y, _x.error.centroidal.base_angular_velocity.z, _x.error.centroidal.momenta.linear.x, _x.error.centroidal.momenta.linear.y, _x.error.centroidal.momenta.linear.z, _x.error.centroidal.momenta.angular.x, _x.error.centroidal.momenta.angular.y, _x.error.centroidal.momenta.angular.z, _x.error.centroidal.momenta_rate.linear.x, _x.error.centroidal.momenta_rate.linear.y, _x.error.centroidal.momenta_rate.linear.z, _x.error.centroidal.momenta_rate.angular.x, _x.error.centroidal.momenta_rate.angular.y, _x.error.centroidal.momenta_rate.angular.z,) = _get_struct_26d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.error.joints = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.JointState()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 32
        (_x.position, _x.velocity, _x.acceleration, _x.effort,) = _get_struct_4d().unpack(str[start:end])
        self.error.joints.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.error.contacts = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.ContactState()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 2
        (_x.type, _x.status,) = _get_struct_2B().unpack(str[start:end])
        _v111 = val1.pose
        _v112 = _v111.position
        _x = _v112
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v113 = _v111.orientation
        _x = _v113
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _v114 = val1.velocity
        _v115 = _v114.linear
        _x = _v115
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v116 = _v114.angular
        _x = _v116
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v117 = val1.wrench
        _v118 = _v117.force
        _x = _v118
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v119 = _v117.torque
        _x = _v119
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v120 = val1.surface_normal
        _x = _v120
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 8
        (val1.friction_coefficient,) = _get_struct_d().unpack(str[start:end])
        self.error.contacts.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.command = []
      for i in range(0, length):
        val1 = whole_body_state_msgs.msg.JointCommand()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 24
        (_x.total, _x.feedforward, _x.feedback,) = _get_struct_3d().unpack(str[start:end])
        self.command.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_26d = None
def _get_struct_26d():
    global _struct_26d
    if _struct_26d is None:
        _struct_26d = struct.Struct("<26d")
    return _struct_26d
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
