(cl:defpackage whole_body_state_msgs-msg
  (:use )
  (:export
   "<CENTROIDALSTATE>"
   "CENTROIDALSTATE"
   "<CONTACTSTATE>"
   "CONTACTSTATE"
   "<JOINTCOMMAND>"
   "JOINTCOMMAND"
   "<JOINTSTATE>"
   "JOINTSTATE"
   "<WHOLEBODYCONTROLLER>"
   "WHOLEBODYCONTROLLER"
   "<WHOLEBODYSTATE>"
   "WHOLEBODYSTATE"
   "<WHOLEBODYTRAJECTORY>"
   "WHOLEBODYTRAJECTORY"
  ))

